baseurl = "https://austindizzy.me"
languageCode = "en-us"
title = "Austin Dizzy"
disqusShortname = "austindizzy"

[author]
name = "Austin Dizzy"

[params]
avatar = "/img/avatar.jpg"
twitter = "@AustinDizzy"
