baseurl = "https://austindizzy.me"
languageCode = "en-us"
title = "Austin Dizzy"
disqusShortname = "austindizzy"

[author]
name = "Austin Dizzy"

[params]
avatar = "https://www.gravatar.com/avatar/04de35a6b83c8a570575aaf0764b8c00.jpg?s=256"
twitter = "@AustinDizzy"
